name: Test
on:
  pull_request:
    branches:
      master
    types: [ready_for_review, opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        version: ["10.0", "11.0", "12.0", "13.0", "14.0"]
    steps:
      - uses: actions/checkout@v2
      - name: Set pyversion
        id: pyversion
        run: |
          if [ ${{ matrix.version }} == 10.0 ]; then
            echo ::set-output name=version::py2;
          elif [ ${{ matrix.version }} == 11.0 ] || [ ${{ matrix.version }} == 12.0 ]; then
            echo ::set-output name=version::py3.6;
          else
            echo ::set-output name=version::py3.8;
          fi
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: gha-oca-mqt-${{ matrix.version }}-buildx
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Test build ${{ matrix.version }}
        uses: docker/build-push-action@v2
        with:
          push: false
          file: ${{ steps.pyversion.outputs.version }}/Dockerfile
          build-args: VERSION=${{ matrix.version }}
          tags: studio73/gha-oca-mqt:${{ matrix.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
