name: Test
on:
  pull_request:
    branches:
      master
    types: [ready_for_review, opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        version: ["10.0", "11.0", "12.0", "13.0", "14.0"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set pyversion
        id: pyversion
        run: if [ ${{ matrix.version }} == 10.0 ]; then echo ::set-output name=version::py2; else echo ::set-output name=version::py3; fi
      - name: Git log
        id: log
        run: echo "::set-output name=message::$(git log --no-merges -1 --oneline)"
      - name: Test build ${{ matrix.version }}
        if: "!contains(steps.log.outputs.message, 'skip build')"
        uses: docker/build-push-action@v1
        with:
          dockerfile: ${{ steps.pyversion.outputs.version }}/Dockerfile
          tags: ${{ matrix.version }}
          push: false
          build_args: VERSION=${{ matrix.version }}
          add_git_labels: true

